---
title: "A Comparative Ecophysiological Survey of Lycophytes, Ferns, and Seed Plants"
author: 
date: 
output:
  word_document:
    reference_docx: manuscriptstyle.docx
  pdf_document: default
  html_document:
    number_sections: yes
csl: new-phytologist.csl
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = '../')
```


# Abstract

/
Key Words:

# Introduction

Our understanding of the ecophysiology of ferns and lycophytes is limited. However, recent studies have shown that these two groups possess an unusual set of functional traits that likely influence their ecology (Brodribb, Watkins, Pinterman, Franks). For example, Watkins has demonstrated that the gametophyte generations of many tropical ferns are markedly desiccation-tolerant, with tolerance being closely linked to ecological preference. In seed plants, desiccation tolerance has been essentially lost from vegetative tissues. Additional work on ferns indicates a tight link between carbon and nitrogen relations with species distribution (Watkins 2005). Work on fern hydraulics is in its early stages; however, a study on tropical ferns suggests that ferns have a significantly more resistive vascular system than seed plants. A recent study on temperate species proposes that ferns are more similar to gymnosperms in their hydraulic properties (Watkins). 

\

	A primary controlling factor in fern hydraulics is stomatal function. Recently, a series of studies have shown that stomatal control of ferns and lycophytes differs from seed plants. Early evidence on fern and lycophyte stomata indicates that these groups have inefficient stomatal systems. Ongoing work by Brodribb et al. is suggesting that ferns and lycophytes may possess a hydropassive mechanism which influences stomatal opening and closing. Unlike seed plants, fern and lycophyte stomata fail to close in response to abscisic acid (ABA) addition. This significant new discovery suggests that at least two fundamentally different mechanisms of stomatal function have evolved in early plants. This, in turn, may impact the differential distribution of ferns and lycophytes relative to seed plants.
	
	\
	
	Studies that examine the comparative physiology of ferns and lycophytes to seed plants are rare. Therefore, it is difficult to derive widely applicable hypotheses of the ecophysiological behavior of these groups. From the few studies we were able to find, ferns and lycophytes appear to have lower photosynthetic rates than seed plants. This would suggest that ferns may be at a competitive disadvantage when growing with seed plants. However, none of these studies have systematically compared the physiology of these groups when growing in similar habitats. 
	
	\
	
	The goal of the current study is to examine the comparative physiology of a number of temperate ferns and lycophytes to angiosperms. We specifically examined several physiological parameters in a pairwise comparison between a fern or a lycophyte and an angiosperm in identical habitats. Given recent suggestions on inefficient stomatal functions, we hypothesized that ferns would have lower photosynthetic rates and stomatal conductance values in comparison to the nearby angiosperms. This, in turn, would impact aspects of leaf morphology (stomatal density), physiology (chlorophyll concentration), nutrient relations (N and P), and carbon relations. We speculate that the differences in physiological function may affect the ecology of these ferns, lycophytes, and angiosperms. 
	
#Methods

## Study site and species

This study was conducted at two sites in upstate New York. Data for most species were gathered at the Edmund Niles Huyck Preserve (ENHP), characterized by mixed hardwood hemlock forests along the Helderberg escarpment in the foothills of the Catskill mountain range. Data from the second site were gathered at a natural area on the campus of Colgate University in Hamilton, New York, situated in the foothills surrounding the Chenango Valley. Forests at this site are younger, but consist of a similar species richness and composition at ENHP. 

\

We examined a series of fern, lycophyte, and angiosperm species at both sites (Table 1). The main focus of this work was to examine ferns relative to light-analogous angiosperms. To accomplish this, we selected a fern species and then located the nearest neighboring angiosperm growing in similar habitat conditions. Surveyed angiosperm taxa were always herbaceous and similar in size and stature to the neighboring fern species. At the ENHP, we sampled across two distinct habitats: understory low-light areas and open, high-light areas. At the Colgate University site, additioanl low-light fern and lycophyte species were surveyed. 

## Physiological Measurements

To generate comparative physiological data, we followed two procedures. First, we generated a series of detailed light response curves for a select number of species from each plant group (fern = , angiosperm = ). Next, to increase our comparative sample size, we surveyed light saturated rates of photosynthesis (A~n~) and stomatal conductance (g~s~) for additional species at the ENHP. All gas exchange parameters were generated using the LiCor 6400 XT Photosynthesis System (Lincoln, NE). 

\

Light response curves were conducted by decreasing the light intensity in the gas exchange cuvette in small step changes. For each light response curve, The CO~2~ in the leaf cuvette was set to a flow rate of 300 $\mu$mol s^-1^ and at ambient atmospheric [CO~2~] (400 ppm). Initial light measurements were made using the built-in quantum sensor to determine typical ambient light levels. These measurements were used to generate light response curves using appropriate light levels for high-light and low-light species separately. The light levels were not identical for each species, with several points being added or subtracted with each run. Broadly, light response curves followed the same template for high light or low light species. For high light species, light levels started at a PPFD of 1500 $\mu$mol m^-1^ s^-1^ and then consisted of ~16 additional steps to O $\mu$mol m^-1^ s^-1^. For low light species, light response curves started at a PPFD of 500 $\mu$mol m^-1^ s^-1^, followed by 13 additional steps to O $\mu$mol m^-1^ s^-1^. The light compensation point (LCP) was calculated as the PPFD at which the net photosynthetic rate equalled zero from the linear phase of each light response curve. Quantum yeild (phi) was calculated as the initial slope of the assimilation rate and dark respiration rate was recorded at the step change where PPFD was 0 $\mu$mol m^-1^ s^-1^.

\

From these light response curves, we developed an understanding of the levels at which low-light and high-light species reached light saturated photosynthetic rates. As a result, additional survey measurments were conducted at at a PPFD of 1200 $\mu$mol m^-1^ s^-1^ for high-light species and 600 $\mu$mol m^-1^ s^-1^ for low-light species. All other cuvette parameters were identical to those used for the light response curves.

temperature?

## Foliar chemistry

Foliar tissue was sampled following gas exchange measurements for all species at ENHP and used for nutrient analyses. Samples were dried to a constant mass and ground using a Wig-L-Bug (Sigma-Aldrich Co. St. Louis, USA). Carbon and nitrogen analyses were measured using a Costech Analytical Elemental Analyzer (Valencia, USA), with the percentage of carbon and nitrogen in samples calculated by comparison with certified standards. Foliar phosphorus concentrations were determined using an ash digestion process (D’Angelo et al., 2001) preceded by colour development and absorbance measurement on an Astoria Paciﬁc colorimetric autoanalyzer (Clackamas, Oregon). 

Photosynthetic nitrogen use efficiency (PNUE) was defined as the ratio of photosynthesis to leaf nitrogen content on a mass basis.*

## Stomatal anatomy

Stomatal density (SD) was measured by directly counting stomata on the abaxial leaf surface under 40x magnification with a field of view of 0.622 mm^2. Stomatal density was calculated from 8 non-overlapping foliar regions for five individuals of each species.

## Statistial analyses

Linear mixed-effect models responses were used to test responses of functional traits to caetgorial fixed effects of plant group and canopy habitat. To test broad differnces in plant groups, species nested within canopy habitats were treated as random effects. To test differences between habitat types (ferns and angiosperms only) species was set as a fixed effect. Explained variance (R2) of mixed models were computed as in Nakagawa and Schielzeth (2013), in which the marginal R2 represents variance explained by fixed factors and the conditional R2 by both fixed and random factors.Tukey’s post-hoc test were performed in conjunction with ANOVA to determine which mean values of functional traits were different among plant groups and canopy habitats with the ‘multcomp’ package (Hothorn et al., 2008). All tests of statistical significance were conducted at an α level of 0.05. All analyses were performed with R 3.5.1 [R cite].


T-tests were performed to test for differences between functional traits, pooled for species, across canopy habitats within angioperm and fern plant groups.

# Results

## Light response curve parameters

In closed canopy environments, angiosperms had significantly higher respiration rates than ferns, which were equal to lycophytes (f2,44= 10.12, p=0.0003). In addition, photosynthetic quantum yield was higher in lycophytes than in angiosperms, whereas ferns had intermediate values between the two (f2,44=5.04, p=0.011). Light compensation points in ferns were equivalent to lycophytes, which both had higher points than angiosperms (f2,44=10.28, p=0.0002). In open canopy environments where lycophytes were lacking, ferns had significantly higher respiration rates (f1,18= 20.87, p= 0.0003), equivalent quantum yields (f1,18= 1.56, p=0.228), and significantly lower light compensation points(f1,18=12.83, p=0.0023). 

\

For angiosperms, species growing in open habitats had significantly more negative respiration rates (t22=-6.88, p<0.0001), equivalent quantum yields(t22=1.89, p=0.072), and higher light compensation points (t22=5.23, p<0.0001) than those angiosperms growing in closed habitats.  

## Physiological surveys

Overall, fern and angiosperm species in open habitats had higher A~n~ than compaable species in low-light habitats (*P* <- 0.0001). Specifically, fern species in high-light habitats had 40.6 % greater A~n~ than in low-light habitats(*P* < 0.0001, t=-4.72), while angiosperm species had 60 % higher A~n~ (*P* < 0.0001, t=-6.97).
Ferns and angiosperms growing in low-light habitats had similar A~n~, however, in open habitats angiosperms had 42.6% higher rates of A~n~ than ferns (canopy x plant group, *P* = 0.043).


Specifically, fern species in high-light habitats had 50.7 % greater g~s~ than in low-light habitats(*P* < 0.0001, t=-4.72), while angiosperm species had 66.9 % higher g~s~ (*P* < 0.0001, t=-4.157).


Ferns growing in open environments had significantly higher maximum area-based photosynthetic rates and stomatal conductances and lower internal leaf CO2 concentrations than those growing in closed canopies (Figure dfg). Angiosperms growing in open canopy environments also had significantly higher maximum area-based photosynthetic rates and stomatal conductances than those growing in closed environments, but there was no significant difference in internal leaf CO2 concentrations between the two light environments. 

\

In open canopy environments, angiosperms, on average, had significantly higher maximum photosynthetic rates and stomatal conductances than ferns growing in similar light conditions. There was no significant difference between the internal CO2 concentrations of angiosperm leaves and fern fronds; however, the statistics hint at a strong trend (Figure asldf). 

\

Across closed canopy environments, some of these differences between angiosperms and ferns break down when the model includes lycophytes. No differences between A~n~ were detected between between plant groups, with a majority of the variation associated with the random effect of individual species. Stomatal conducance was higher in angiosperms than lycophytes, while ferns were not different from either plant group (*P* = 0.005). The leaf internal CO~2~ concentrations were not different between plant groups, with a majority of the variation associated with the random effect of individual species.

# Stoichiometry

In open canopy environments, ferns had significantly lower phosphorus concentrations than those growing in closed canopies. Angiosperms had no significant difference across the light gradient. In both environments, ferns and lycophytes do not differ significantly, but both have significantly lower phosphorus levels than angiosperms (Figure asdf). Ferns in open light environments have significantly lower nitrogen levels than those ferns growing in closed light environments; the same is true of angiosperms. Lycophytes have significantly lower nitrogen levels than ferns and angiosperms, which do not statistically differ, in both light conditions (Figure adf). 

\

	Neither ferns nor angiosperms differ within their classifications significantly across the two light environments in their nitrogen to phosphorus ratio (N:P). In open light environments, ferns have significantly higher N:P ratios than angiosperms. In closed canopy environments, ferns do not differ from angiosperms significantly in their N:P ratios, but do differ from lycophytes. Also, lycophytes and angiosperms do not differ significantly. 

\

	Ferns in open light canopies have significantly higher carbon to nitrogen ratios (C:N) than those growing in closed canopies, while angiosperms do not differ across the light gradient. Also, ferns have significantly higher C:N ratios than corresponding angiosperms in open light environments. In closed canopies, lycophytes have the highest C:N ratios and differ significantly from both ferns and angiosperms, which do not significantly differ.

## Physiological parameters

Overall, no differences where detected in stomatal densities between species growing open canopy and closed canopy habitats. Specifically, differences in stomatal densities were not detected for either fern nor angiosperms species between the two habitats. However, in both open and closed environments, ferns had significantly lower stomatal densities than analogous angiosperms () (Figure asdfs). In

Similarly, ferns displayed a significantly lower SPAD index, a measurement of chlorophyll concentration, in open canopy environments versus closed canopies. Angiosperms showed no significant difference across the light gradient. In open environments, ferns had significantly lower SPAD index values than corresponding angiosperms, while the reverse was true in closed canopy habitats, with ferns displaying significantly higher values than analogous angiosperms (Figure asdfkj). 
